import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Providers from "./Providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";

const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai'],            // รองรับภาษาไทย
  weight: ['400', '700'],       // น้ำหนักฟอนต์ที่ต้องการ
  display: 'swap',              // ปรับพฤติกรรมการโหลดฟอนต์
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${notoSansThai.className} antialiased`}
        >
          <Providers>
             <Suspense fallback={<div>Loading navbar...</div>}>
              <Navbar />
            </Suspense>
            <main className="container">
              {children}
              <Toaster />
            </main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
